<#
.SYNOPSIS
    Restores x500 proxy addresses that the sync removed from on-premises AD accounts.

.DESCRIPTION
    IdentitySyncPro wrote proxyAddresses with an LDAP Replace containing only the two mapped
    SMTP addresses, which discarded each mailbox's x500 entry. x500 is the mailbox
    LegacyExchangeDN; Outlook uses it to resolve replies to older mail, free/busy lookups, and
    routing for migrated mailboxes.

    The value CANNOT be reconstructed -- the cn=<hash>-<alias> segment is generated by Exchange.
    This script reads each mailbox's LegacyExchangeDN from Exchange Online (which keeps it as a
    property of its own, separate from EmailAddresses) and writes it back on-premises as an
    x500: entry.

    Report-only by default. It never removes anything: the x500 is ADDED to whatever the
    account currently has.

.PARAMETER Apply
    Actually write to AD. Without it the script only reports what it would do.

.PARAMETER Accounts
    sAMAccountNames to process. Defaults to the accounts identified in the 2026-07-20 and
    2026-07-22 sync logs.

.PARAMETER LogPath
    CSV written with the outcome for every account.

.EXAMPLE
    .\Restore-X500Addresses.ps1
    Reports what would change. Run this first and read the output.

.EXAMPLE
    .\Restore-X500Addresses.ps1 -Apply
    Performs the restore.

.NOTES
    Requires: RSAT ActiveDirectory module, ExchangeOnlineManagement module, and an account with
    write access to the users' proxyAddresses.

    ACT SOON: if Entra Connect (AAD Connect) has not yet synced the stripped value upward, the
    cloud object may still hold it. LegacyExchangeDN itself is a mailbox property and is not
    removed by a proxyAddresses change, so it is normally still readable either way.
#>

[CmdletBinding()]
param(
    [switch]$Apply,

    # Domain controller / domain holding the accounts. REQUIRED when they do not live in the
    # domain this workstation is joined to: student accounts are in std.nu.edu.sa while the
    # workstation is joined to nu.edu.sa, so an unqualified Get-ADUser searches the wrong
    # directory and reports every account as missing.
    [string]$Server = 'std.nu.edu.sa',

    # Credentials for $Server. Needed when the current logon has no rights in that domain.
    [System.Management.Automation.PSCredential]$Credential,

    [string[]]$Accounts = @(
        # From the 2026-07-20 21:41 sync run (14 accounts)
        '435302568','442306049','443300129','443403559','444300775',
        '444305431','445302034','445302267','445302669','446201153',
        '446202605','447100460','447205362','447300003',
        # From the 2026-07-22 16:40 sync run (1 account)
        '431840119'
    ),

    [string]$LogPath = ".\x500-restore-$(Get-Date -Format 'yyyyMMdd-HHmmss').csv"
)

$ErrorActionPreference = 'Stop'

function Write-Section($text) {
    Write-Host ""
    Write-Host ("=" * 78) -ForegroundColor DarkCyan
    Write-Host $text -ForegroundColor Cyan
    Write-Host ("=" * 78) -ForegroundColor DarkCyan
}

Write-Section "x500 restore -- $(if ($Apply) { 'APPLY MODE (will write to AD)' } else { 'REPORT ONLY' })"
Write-Host "Accounts to check: $($Accounts.Count)"

# --- Prerequisites -----------------------------------------------
foreach ($m in 'ActiveDirectory','ExchangeOnlineManagement') {
    if (-not (Get-Module -ListAvailable -Name $m)) {
        throw "Required module '$m' is not installed. Install it and re-run."
    }
}
Import-Module ActiveDirectory -ErrorAction Stop

# Common arguments for every AD call, so the domain is never left to chance.
$adArgs = @{ Server = $Server }
if ($Credential) { $adArgs['Credential'] = $Credential }

Write-Host "AD domain/server: $Server" -ForegroundColor Cyan

# Fail fast on a bad domain. Without this the script queries the wrong directory and reports
# every account as "not found" -- which reads like the accounts were deleted.
try {
    Get-ADDomain @adArgs -ErrorAction Stop | Out-Null
    Write-Host "AD: connected." -ForegroundColor Green
}
catch {
    throw "Cannot reach AD domain '$Server': $($_.Exception.Message)`n" +
          "Pass the correct one with -Server (student accounts live in std.nu.edu.sa), " +
          "and -Credential if the current logon has no rights there."
}

# Reuse an existing Exchange Online session if one is already connected.
try {
    Get-Mailbox -ResultSize 1 -ErrorAction Stop | Out-Null
    Write-Host "Exchange Online: using existing session." -ForegroundColor Green
}
catch {
    Write-Host "Connecting to Exchange Online..." -ForegroundColor Yellow
    Import-Module ExchangeOnlineManagement -ErrorAction Stop
    Connect-ExchangeOnline -ShowBanner:$false -ErrorAction Stop
}

# --- Process -----------------------------------------------------
$results = @()

foreach ($sam in $Accounts) {

    $row = [ordered]@{
        SamAccountName    = $sam
        Status            = ''
        X500Restored      = ''
        ExistingAddresses = ''
        Detail            = ''
    }

    try {
        $user = Get-ADUser @adArgs -Filter "sAMAccountName -eq '$sam'" -Properties proxyAddresses, mail -ErrorAction Stop

        if (-not $user) {
            $row.Status = 'NotFoundInAD'
            $row.Detail = "No account with this sAMAccountName in '$Server'"
            $results += [pscustomobject]$row
            Write-Host "[$sam] not found in $Server" -ForegroundColor DarkYellow
            continue
        }

        $current = @($user.proxyAddresses)
        $row.ExistingAddresses = ($current -join ' | ')

        # Already has an x500? Then this account was never stripped (or is already restored).
        if ($current | Where-Object { $_ -like 'x500:*' }) {
            $row.Status = 'AlreadyPresent'
            $row.Detail = 'Account already has an x500 address -- nothing to do'
            $results += [pscustomobject]$row
            Write-Host "[$sam] x500 already present -- skipped" -ForegroundColor DarkGray
            continue
        }

        # The authoritative source. LegacyExchangeDN is a mailbox property in its own right and
        # is not affected by a proxyAddresses rewrite, so it survives the incident.
        $mailbox = Get-Mailbox -Identity $sam -ErrorAction SilentlyContinue
        if (-not $mailbox) {
            # Fall back to the primary SMTP address, in case the alias differs from sAMAccountName.
            if ($user.mail) { $mailbox = Get-Mailbox -Identity $user.mail -ErrorAction SilentlyContinue }
        }

        if (-not $mailbox -or -not $mailbox.LegacyExchangeDN) {
            $row.Status = 'NoSourceValue'
            $row.Detail = 'Could not read LegacyExchangeDN from Exchange Online -- restore manually from a backup'
            $results += [pscustomobject]$row
            Write-Host "[$sam] LegacyExchangeDN unavailable -- MANUAL ACTION NEEDED" -ForegroundColor Red
            continue
        }

        $x500 = "x500:$($mailbox.LegacyExchangeDN)"
        $row.X500Restored = $x500

        if (-not $Apply) {
            $row.Status = 'WouldRestore'
            $row.Detail = 'Report only -- re-run with -Apply to write'
            $results += [pscustomobject]$row
            Write-Host "[$sam] would add: $x500" -ForegroundColor Yellow
            continue
        }

        # ADD only. Never touches the existing values.
        Set-ADUser @adArgs -Identity $user.DistinguishedName -Add @{ proxyAddresses = $x500 } -ErrorAction Stop

        $row.Status = 'Restored'
        $row.Detail = 'x500 added to proxyAddresses'
        $results += [pscustomobject]$row
        Write-Host "[$sam] RESTORED: $x500" -ForegroundColor Green
    }
    catch {
        $row.Status = 'Error'
        $row.Detail = $_.Exception.Message
        $results += [pscustomobject]$row
        Write-Host "[$sam] ERROR: $($_.Exception.Message)" -ForegroundColor Red
    }
}

# --- Summary -----------------------------------------------------
Write-Section "Summary"
$results | Group-Object Status | Sort-Object Count -Descending | ForEach-Object {
    Write-Host ("  {0,-16} {1}" -f $_.Name, $_.Count)
}

$results | Export-Csv -Path $LogPath -NoTypeInformation -Encoding UTF8
Write-Host ""
Write-Host "Full results: $LogPath" -ForegroundColor Cyan

if (-not $Apply) {
    Write-Host ""
    Write-Host "REPORT ONLY -- nothing was changed. Review the CSV, then re-run with -Apply." -ForegroundColor Yellow
}
else {
    Write-Host ""
    Write-Host "Done. Verify one account before assuming the rest are correct:" -ForegroundColor Yellow
    Write-Host "  Get-ADUser $($Accounts[0]) -Server $Server -Properties proxyAddresses | Select -Expand proxyAddresses"
    Write-Host ""
    Write-Host "Then let Entra Connect run a delta sync so the cloud picks the value back up." -ForegroundColor Yellow
}

if ($results | Where-Object Status -eq 'NoSourceValue') {
    Write-Host ""
    Write-Host "Some accounts had no readable LegacyExchangeDN. Those cannot be reconstructed --" -ForegroundColor Red
    Write-Host "recover them from an AD backup or a pre-incident export." -ForegroundColor Red
}
